"""
WstETHWmaticLoop Strategy Package.

Generated by: almanak strat new
"""

try:
    from .strategy import WstETHWmaticLoopStrategy
except ImportError:
    from strategy import WstETHWmaticLoopStrategy

__all__ = [
    "WstETHWmaticLoopStrategy",
]
